[package]
name = "login-items-manager"
version = "0.1.0"
description = "A cli-tool to manage login items on macOS."
authors = ["Swizzer <kyoshaft@outlook.com>"]
license = "AGPL-3.0-only"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.29.0"
ratatui = "0.30.0"

# Read the optimization guideline for more details: https://ratatui.rs/recipes/apps/release-your-app/#optimizations
[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
